export const CASE_GET_PRODUCTS = "CASE_GET_PRODUCTS";

export const CASE_GET_ONE_PRODUCT = "CASE_GET_ONE_PRODUCT";

export const CASE_GET_CART = "GET_CART";

export const CASE_GET_FAVOURITES = "GET_FAVOURITES";
